### ISSUE TITLE
Issue...

### ISSUE THREAD

**Issue by 0u44** [Zacky2613/Zacky2613#1]
Just wanted to say, the profile views you got could be from you looking at your page, the amount of times you refresh also add views (tested on my profile)

**Comment by Zacky2613** [comment]
I will say that most of my profile views are from me looking at it myself. However, it's just browsing to get to other repos of mine, I'm not purposefully trying to inflate the numbers. It is a flaw with the profile view counter but there's nothing that can be done about it sadly. 

https://github.com/antonkomarev/github-profile-views-counter#why-does-the-counter-increase-every-time-the-page-is-reloaded This explains the issue.
